# Generated by Django 4.1 on 2022-08-19 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clsroom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='cls_id',
            field=models.CharField(default='254f3f1788-1ff5-11ed-b73e-2d8765cb10b378', editable=False, max_length=40, primary_key=True, serialize=False),
        ),
    ]
