# Generated by Django 3.2.9 on 2022-01-10 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clsroom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='cls_id',
            field=models.CharField(default='51e0bb674e-71f3-11ec-87bd-74c63bf6c54248', editable=False, max_length=40, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='cid',
            field=models.CharField(default='64e0ba4288-71f3-11ec-87bd-74c63bf6c54242', editable=False, max_length=40, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='mid',
            field=models.CharField(default='71e0ba791a-71f3-11ec-87bd-74c63bf6c54242', editable=False, max_length=40, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='mid',
            field=models.CharField(default='94e0baf214-71f3-11ec-87bd-74c63bf6c54217', editable=False, max_length=40, primary_key=True, serialize=False),
        ),
    ]
