# Generated by Django 3.2.9 on 2022-03-08 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clsroom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='cls_id',
            field=models.CharField(default='354700c0f8-9f08-11ec-a27d-74c63bf6c54227', editable=False, max_length=40, primary_key=True, serialize=False),
        ),
    ]
