# Generated by Django 3.2.9 on 2022-03-08 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clsroom', '0002_alter_classroom_cls_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='cls_id',
            field=models.CharField(default='5200db29ba-9f0d-11ec-9d7b-74c63bf6c54218', editable=False, max_length=40, primary_key=True, serialize=False),
        ),
    ]
