# Generated by Django 3.2.9 on 2022-01-10 09:13

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clsroom', '0002_auto_20220110_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='cls_room_id',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=40), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='cls_id',
            field=models.CharField(default='15820277ae-71f5-11ec-9e87-74c63bf6c54247', editable=False, max_length=40, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='cid',
            field=models.CharField(default='7282015068-71f5-11ec-9e87-74c63bf6c54250', editable=False, max_length=40, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='mid',
            field=models.CharField(default='43820188ee-71f5-11ec-9e87-74c63bf6c54239', editable=False, max_length=40, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='mid',
            field=models.CharField(default='178202030a-71f5-11ec-9e87-74c63bf6c54284', editable=False, max_length=40, primary_key=True, serialize=False),
        ),
    ]
