# Generated by Django 3.2.9 on 2021-11-25 14:17

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clsroom', '0002_alter_account_cls_room_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='cls_room_id',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=30), default=list, size=None),
        ),
    ]
