# Generated by Django 3.2.9 on 2022-01-10 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clsroom', '0003_auto_20220110_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='cls_id',
            field=models.CharField(default='81c7aa25d2-71f9-11ec-ac9f-74c63bf6c54229', editable=False, max_length=40, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='cid',
            field=models.CharField(default='26c7a9003a-71f9-11ec-ac9f-74c63bf6c54241', editable=False, max_length=40, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='mid',
            field=models.CharField(default='94c7a93780-71f9-11ec-ac9f-74c63bf6c54238', editable=False, max_length=40, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='mid',
            field=models.CharField(default='33c7a9b02a-71f9-11ec-ac9f-74c63bf6c54215', editable=False, max_length=40, primary_key=True, serialize=False),
        ),
    ]
