# Generated by Django 3.2.9 on 2021-11-25 19:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('clsroom', '0004_classroom_comment_mediafile_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='class_code',
            field=models.UUIDField(blank=True, default=uuid.uuid1, editable=False, unique=True),
        ),
    ]
