# Generated by Django 3.2.9 on 2021-11-25 20:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clsroom', '0005_classroom_class_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='media_files',
            field=models.ManyToManyField(blank=True, related_name='mediaFiles', to='clsroom.MediaFile'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='messages',
            field=models.ManyToManyField(blank=True, related_name='classMessage', to='clsroom.Message'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='students', to=settings.AUTH_USER_MODEL),
        ),
    ]
