# Generated by Django 3.2.9 on 2022-01-10 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clsroom', '0005_auto_20220110_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='cls_id',
            field=models.CharField(default='3381468882-71fa-11ec-ba3e-74c63bf6c54256', editable=False, max_length=40, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='cid',
            field=models.CharField(default='40814518bc-71fa-11ec-ba3e-74c63bf6c54243', editable=False, max_length=40, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='mid',
            field=models.CharField(default='51814562ae-71fa-11ec-ba3e-74c63bf6c54275', editable=False, max_length=40, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='mid',
            field=models.CharField(default='658145f73c-71fa-11ec-ba3e-74c63bf6c54256', editable=False, max_length=40, primary_key=True, serialize=False),
        ),
    ]
