# Generated by Django 3.2.9 on 2022-01-10 09:57

import clsroom.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clsroom', '0006_auto_20220110_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='cls_id',
            field=models.CharField(default='39b0116ad2-71fb-11ec-86a8-74c63bf6c54240', editable=False, max_length=40, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='cid',
            field=models.CharField(default=clsroom.utils.generate_uid, editable=False, max_length=40, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='mid',
            field=models.CharField(default=clsroom.utils.generate_uid, editable=False, max_length=40, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='mid',
            field=models.CharField(default=clsroom.utils.generate_uid, editable=False, max_length=40, primary_key=True, serialize=False),
        ),
    ]
