# Generated by Django 3.2.9 on 2021-11-25 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clsroom', '0006_auto_20211125_2055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='class_code',
        ),
    ]
