# Generated by Django 3.2.9 on 2021-11-25 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clsroom', '0008_auto_20211125_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='cls_id',
            field=models.CharField(default='<function uuid1 at 0x7fb7a989e310>', editable=False, max_length=34, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='cid',
            field=models.CharField(default='<function uuid1 at 0x7fb7a989e310>', editable=False, max_length=34, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='mid',
            field=models.CharField(default='<function uuid1 at 0x7fb7a989e310>', editable=False, max_length=34, primary_key=True, serialize=False),
        ),
    ]
