# Generated by Django 3.2.9 on 2021-11-25 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clsroom', '0009_auto_20211125_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='cls_id',
            field=models.CharField(default='007d8882-4e45-11ec-a14d-74c63bf6c542', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='cid',
            field=models.CharField(default='007c4260-4e45-11ec-a14d-74c63bf6c542', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='mid',
            field=models.CharField(default='007cfe8a-4e45-11ec-a14d-74c63bf6c542', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
    ]
