# Generated by Django 3.2.9 on 2021-11-25 23:45

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clsroom', '0010_auto_20211125_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='cls_room_id',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=36), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='cls_id',
            field=models.CharField(default='b3b35de2-4e49-11ec-a293-74c63bf6c542', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='cid',
            field=models.CharField(default='b3b24056-4e49-11ec-a293-74c63bf6c542', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='mid',
            field=models.CharField(default='b3b2e830-4e49-11ec-a293-74c63bf6c542', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
    ]
