# Generated by Django 3.2.9 on 2021-11-26 01:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clsroom', '0011_auto_20211125_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='blocked_accounts',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default=None, max_length=36), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='cls_id',
            field=models.CharField(default='849e89e2-4e57-11ec-97be-74c63bf6c542', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='cid',
            field=models.CharField(default='849c65f4-4e57-11ec-97be-74c63bf6c542', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='mid',
            field=models.CharField(default='849dc688-4e57-11ec-97be-74c63bf6c542', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
    ]
