# Generated by Django 3.2.9 on 2021-11-27 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clsroom', '0014_auto_20211127_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='cls_id',
            field=models.CharField(default='01ad4edc-4f61-11ec-8857-74c63bf6c542', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='cid',
            field=models.CharField(default='01ac2e62-4f61-11ec-8857-74c63bf6c542', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='mid',
            field=models.CharField(default='01acd8ee-4f61-11ec-8857-74c63bf6c542', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
    ]
