# Generated by Django 3.2.9 on 2021-11-27 09:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clsroom', '0015_auto_20211127_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='classroom',
            name='cls_id',
            field=models.CharField(default='bf54de36-4f62-11ec-a995-74c63bf6c542', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='cid',
            field=models.CharField(default='bf53c596-4f62-11ec-a995-74c63bf6c542', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='mid',
            field=models.CharField(default='bf546aa0-4f62-11ec-a995-74c63bf6c542', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
    ]
