# Generated by Django 3.2.9 on 2021-11-28 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clsroom', '0017_auto_20211127_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='cls_id',
            field=models.CharField(default='f58734b8-5075-11ec-9adb-74c63bf6c542', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='cid',
            field=models.CharField(default=36, editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='cls_id',
            field=models.CharField(max_length=36),
        ),
        migrations.AlterField(
            model_name='comment',
            name='mid',
            field=models.CharField(max_length=36),
        ),
        migrations.AlterField(
            model_name='message',
            name='mid',
            field=models.CharField(default='f586bae2-5075-11ec-9adb-74c63bf6c542', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
    ]
