# Generated by Django 3.2.9 on 2021-11-29 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clsroom', '0018_auto_20211128_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='cls_id',
            field=models.CharField(default='02a54480-50e1-11ec-8d3a-74c63bf6c542', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='mid',
            field=models.CharField(default='02a4ccda-50e1-11ec-8d3a-74c63bf6c542', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
    ]
