# Generated by Django 3.2.9 on 2021-11-29 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clsroom', '0019_auto_20211129_0653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='cls_id',
        ),
        migrations.AlterField(
            model_name='classroom',
            name='cls_id',
            field=models.CharField(default='541fa120-50e1-11ec-bb28-74c63bf6c542', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='mid',
            field=models.CharField(default='541ee744-50e1-11ec-bb28-74c63bf6c542', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
    ]
