# Generated by Django 3.2.9 on 2021-11-29 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clsroom', '0021_auto_20211129_0656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='cls_id',
            field=models.CharField(default='543d02cc-50e3-11ec-93c5-74c63bf6c542', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='cid',
            field=models.CharField(default='543be52c-50e3-11ec-93c5-74c63bf6c542', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='mid',
            field=models.CharField(default='543c83e2-50e3-11ec-93c5-74c63bf6c542', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
    ]
